# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Social Station - Fans Follow
email: follow@social-station.com
description: The Greatest Social Media Hub in the Galaxy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qdup.github.io/social-station/" # the base hostname & protocol for your site
twitter_username: steadynow
github_username:  steadynow

# Build settings
markdown: kramdown
exclude: ['node_modules', 'css', '_scss']
keep_files: ['_site/css']